### ISSUE TITLE
Greybel interpreter/debugger hangs and is unkillable

### ISSUE THREAD

**Issue by Olipro** [ayecue/greybel-vs#119]
Sadly don't have an exact cause as to _what_ is causing this. I'm throwing out a guess here because I don't _think_ I have any cycles, but, could cyclic `//include` blow it up?

Anyway, not having much to go on, other than knowing that my code doesn't do this in-game - when this happens, the interpreter goes zombie mode. You can hit the stop button in VS, and after a few seconds, VSCode will exit the debugging state. 

However, you _cannot_ start any more debug sessions without a full restart of VSCode. CPU Usage remains pegged at a full core, too, so it's definitely still running.

**Comment by ayecue** [comment]
Well I think it might be related to my recent change which is about batching iterations to improve script execution speed. It could be that the event loop is filling up too much blocking any interaction.

Could you check if you have the same experience when using version 1.9.3?

**Comment by Olipro** [comment]
Yep, `1.9.3` is able to successfully start the application, no observable issues.

**Comment by ayecue** [comment]
I'll revert the changes with the next update. Sorry for the inconvinience.

**Comment by ayecue** [comment]
1.9.5 - https://github.com/ayecue/greybel-vs/pull/118 just got merged and should be soon available. So the issue should be fixed.

**Comment by Olipro** [comment]
'tis indeed. Another one closed out!

**Comment by Olipro** [comment]
Reopening this sadly. I've done it again - same issue as before, and still not sure where.

For reference, I'm now on `1.9.6`

**Comment by Olipro** [comment]
OK, I have a bit more for you to work with, this is happening when including the `JSON` source code (linked here: https://gist.github.com/Olipro/8e323425d6018f18c0791c71606406da )

Now, here's the interesting bit: At the end of the file, you'll see it calls `__scope` then does `__scope = null`.

If I change that to:

```Lua
if not globals.hasIndex("JSON") then __scope
globals.remove("__scope")
```

Then it works fine.

Sadly, this _still_ isn't the full picture, something _special_ is happening in the source file where I include JSON, but I don't know what. Creating a trivial file that just includes the JSON source executes and returns without issue - but hopefully this gives you something to go on.

**Comment by ayecue** [comment]
Do you have an example payload for your parser that causes the hang up?

**Comment by Olipro** [comment]
I'll send it to you on Discord since it's a few files
